# coding: utf-8

"""
    Amazon Shipping API

    The Amazon Shipping API is designed to support outbound shipping use cases both for orders originating on Amazon-owned marketplaces as well as external channels/marketplaces. With these APIs, you can request shipping rates, create shipments, cancel shipments, and track shipments.  # noqa: E501

    OpenAPI spec version: v2
    Contact: swa-api-core@amazon.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CarrierAccount(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'carrier_account_id': 'AccountId',
        'carrier_id': 'CarrierId'
    }

    attribute_map = {
        'carrier_account_id': 'carrierAccountId',
        'carrier_id': 'carrierId'
    }

    def __init__(self, carrier_account_id=None, carrier_id=None):  # noqa: E501
        """CarrierAccount - a model defined in Swagger"""  # noqa: E501
        self._carrier_account_id = None
        self._carrier_id = None
        self.discriminator = None
        self.carrier_account_id = carrier_account_id
        self.carrier_id = carrier_id

    @property
    def carrier_account_id(self):
        """Gets the carrier_account_id of this CarrierAccount.  # noqa: E501


        :return: The carrier_account_id of this CarrierAccount.  # noqa: E501
        :rtype: AccountId
        """
        return self._carrier_account_id

    @carrier_account_id.setter
    def carrier_account_id(self, carrier_account_id):
        """Sets the carrier_account_id of this CarrierAccount.


        :param carrier_account_id: The carrier_account_id of this CarrierAccount.  # noqa: E501
        :type: AccountId
        """
        if carrier_account_id is None:
            raise ValueError("Invalid value for `carrier_account_id`, must not be `None`")  # noqa: E501

        self._carrier_account_id = carrier_account_id

    @property
    def carrier_id(self):
        """Gets the carrier_id of this CarrierAccount.  # noqa: E501


        :return: The carrier_id of this CarrierAccount.  # noqa: E501
        :rtype: CarrierId
        """
        return self._carrier_id

    @carrier_id.setter
    def carrier_id(self, carrier_id):
        """Sets the carrier_id of this CarrierAccount.


        :param carrier_id: The carrier_id of this CarrierAccount.  # noqa: E501
        :type: CarrierId
        """
        if carrier_id is None:
            raise ValueError("Invalid value for `carrier_id`, must not be `None`")  # noqa: E501

        self._carrier_id = carrier_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CarrierAccount, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CarrierAccount):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
