# coding: utf-8

"""
    Amazon Shipping API

    The Amazon Shipping API is designed to support outbound shipping use cases both for orders originating on Amazon-owned marketplaces as well as external channels/marketplaces. With these APIs, you can request shipping rates, create shipments, cancel shipments, and track shipments.  # noqa: E501

    OpenAPI spec version: v2
    Contact: swa-api-core@amazon.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import amazon_shipping
from amazon_shipping.api.shipping_api import ShippingApi  # noqa: E501
from amazon_shipping.rest import ApiException


class TestShippingApi(unittest.TestCase):
    """ShippingApi unit test stubs"""

    def setUp(self):
        self.api = ShippingApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_cancel_shipment(self):
        """Test case for cancel_shipment

        """
        pass

    def test_direct_purchase_shipment(self):
        """Test case for direct_purchase_shipment

        """
        pass

    def test_generate_collection_form(self):
        """Test case for generate_collection_form

        """
        pass

    def test_get_access_points(self):
        """Test case for get_access_points

        """
        pass

    def test_get_additional_inputs(self):
        """Test case for get_additional_inputs

        """
        pass

    def test_get_carrier_account_form_inputs(self):
        """Test case for get_carrier_account_form_inputs

        """
        pass

    def test_get_carrier_accounts(self):
        """Test case for get_carrier_accounts

        """
        pass

    def test_get_collection_form(self):
        """Test case for get_collection_form

        """
        pass

    def test_get_collection_form_history(self):
        """Test case for get_collection_form_history

        """
        pass

    def test_get_rates(self):
        """Test case for get_rates

        """
        pass

    def test_get_shipment_documents(self):
        """Test case for get_shipment_documents

        """
        pass

    def test_get_tracking(self):
        """Test case for get_tracking

        """
        pass

    def test_get_unmanifested_shipments(self):
        """Test case for get_unmanifested_shipments

        """
        pass

    def test_link_carrier_account(self):
        """Test case for link_carrier_account

        """
        pass

    def test_one_click_shipment(self):
        """Test case for one_click_shipment

        """
        pass

    def test_purchase_shipment(self):
        """Test case for purchase_shipment

        """
        pass

    def test_unlink_carrier_account(self):
        """Test case for unlink_carrier_account

        """
        pass


if __name__ == '__main__':
    unittest.main()
